# Generated by Django 3.2.7 on 2021-10-04 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Журналист',
                'verbose_name_plural': 'Журналисты',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='journalist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.journalist', verbose_name='Журналист'),
        ),
    ]
